bnrepo-test-local:
  type: local
  dir: /tmp/bnrepo-test
  create: true

bnrepo-test-local-2:
  type: local
  dir: /tmp/bnrepo-test2
  create: true

bnrepo-test-s3-DISABLED:
  type: s3
  aws_key: AWS_KEY
  aws_secret: AWS_SECRET
  bucket: bnrepo-test
  dir: bnrepo-test
  create: true
  use_old_version: false
  options:
    default_acl: public-read #bucket-owner-full-control[DEFAULT]|private|public-read|public-read-write|authenticated-read|bucket-owner-read

bnrepo-test-ftp-DISABLED:
  type: ftp
  host: HOST
  username: USERNAME
  password: PASSWORD
  dir: /bnrepo-test
  passive: false

bnrepo-test-sftp-DISABLED:
  type: sftp
  host: HOST
  port: PORT
  dir: /bnrepo-test
  username: USERNAME
  password: PASSWORD
